### ISSUE TITLE
Consider adding support for ThemeMode.system?

### ISSUE THREAD

**Issue by charles0122** [sunarya-thito/shadcn_flutter#86]
The current themes are all set in colorScheme, including light and dark modes. It seems difficult to update the theme according to the system.

**Comment by charles0122** [comment]
Great, currently the themeMode.system effect is ok, when I select themeMode.system in my app, it works fine, when the system is light mode, I can switch thememode to thememode.dark, but when my system is dark mode, I switch thememode to thememode.light seems to be invalid.

**Comment by charles0122** [comment]
```yaml
  shadcn_flutter:
    git:
      url: https://github.com/sunarya-thito/shadcn_flutter.git
      ref: 923da9a4cf95aefa1283f8d9870af65114277f98
```

flutter sdk:3.24.3
platform: ios
